### ISSUE TITLE
For 0.2.0 release

### ISSUE THREAD

**Issue by OkonSamuel** [JuliaPy/PyCallJLD.jl#13]
@JuliaRegistrator register

**Comment by OkonSamuel** [comment]
@cstjean. I forgot that am not a member of this organization. I guess you have to do it.

**Comment by cstjean** [comment]
Yes, but the Project.toml file is missing.

**Comment by OkonSamuel** [comment]
@cstjean . I have added the **Project.toml** file and fixed another deprecation [here](https://github.com/JuliaPy/PyCallJLD.jl/pull/14)

**Comment by cstjean** [comment]
Thank you!
