### ISSUE TITLE
With python 3.6 cPickle cannot be found, instead one have to import pickle

### ISSUE THREAD

**Issue by stakaz** [JuliaPy/PyCallJLD.jl#6]
Hello, I cannot precompile the module when using python 3.6 because it cannot found the `cPickle` module.
Here is the error code:

```julia
ERROR: LoadError: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'cPickle'",)

Stacktrace:
 [1] pyerr_check at /home/gluon/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /home/gluon/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /home/gluon/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] pyimport(::String) at /home/gluon/.julia/v0.6/PyCall/src/PyCall.jl:374
 [5] __init__() at /home/gluon/.julia/v0.6/PyCallJLD/src/PyCallJLD.jl:11
 [6] _include_from_serialized(::String) at ./loading.jl:157
 [7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [8] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
 [9] _require(::Symbol) at ./loading.jl:441
 [10] require(::Symbol) at ./loading.jl:405
 [11] include_from_node1(::String) at ./loading.jl:576
 [12] include(::String) at ./sysimg.jl:14
 [13] anonymous at ./<missing>:2
during initialization of module PyCallJLD
```

I have searched across the internet and found that for python 3.x one has to import `pickle` and it will fall down to `cPickle` when possible.
Indeed changing the import function in `PyCallJLD.jl` to `pickle` allows to compile probably. Any Chance to have it in the version installed by `Pkg`?

**Comment by cstjean** [comment]
Sure, and thank you for the detailed report. We can get the Python version from `sys.version_info.major`. Something like `pickle_module = pyimport("sys")[:version_info][:major] == 2 ? "cPickle" : "pickle"` should work. Would you like to make a pull request? This package has very simple code.

**Comment by stakaz** [comment]
For the moment I am busy, I have changed it to `pickle` in my local code but I have no time for testing it with different python versions on my own. Also I am really new all this git stuff.

**Comment by stevengj** [comment]
Note that this logic is [already implemented](https://github.com/JuliaPy/PyCall.jl/blob/55648f27682835cbe886b9c6de39a25ad8c8c1bd/src/serialize.jl) in the PyCall `serialize` function.   You can get the Pickle module with `PyCall.pickle()`.

Rather than calling `pickle` yourself, however, maybe just call `serialize`?

**Comment by cstjean** [comment]
That was [discussed before](https://github.com/JuliaPy/PyCallJLD.jl/issues/2). I'm fine with `serialize`. The less code, the better.

**Comment by dungkarl** [comment]
you try : import pickle as cPickle

**Comment by aneeshp1994** [comment]
In `python3`, `_pickle` does similar function as of `cPickle`.

**Comment by cstjean** [comment]
> A common pattern in Python 2.x is to have one version of a module implemented in pure Python, with an optional accelerated version implemented as a C extension; for example, pickle and cPickle. This places the burden of importing the accelerated version and falling back on the pure Python version on each user of these modules. In Python 3.0, the accelerated versions are considered implementation details of the pure Python versions. Users should always import the standard version, which attempts to import the accelerated version and falls back to the pure Python version. The pickle / cPickle pair received this treatment. The profile module is on the list for 3.1. The StringIO module has been turned into a class in the io module.

https://docs.python.org/3.1/whatsnew/3.0.html#library-changes

Sounds like we're doing the right thing?
